node_js:
  - "node"
language: node_js
install:
  - npm install -g purescript pulp bower spago
  - bower install
  - spago -x test.dhall install
script:
  - pulp test
  - rm -r output/ # clean build objects
  - spago -x test.dhall test
